# Welcome to Jekyll!
# Site settings
title: Redcar Group Dev
description: 
owner: Redcar Group # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: inquiry@redcargroup.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.redcargroup.com" # the base hostname & protocol for your site
social:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
